[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.distutils"  # <- Añadido aquí
]

[phases.install]
commands = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
command = "python kick_view.py"

[env]
PATH = "/opt/venv/bin:$PATH"

