[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.distutils",
  "chromium"
]

[phases.install]
commands = [
  # Usamos python3.11 explícito para crear venv
  "python3.11 -m venv /opt/venv",

  # Activamos e instalamos
  ". /opt/venv/bin/activate && pip install --upgrade pip",

  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
# Ejecutamos con el python del venv explícitamente
command = "/opt/venv/bin/python kick_view.py"

[env]
PATH = "/opt/venv/bin:$PATH"
